export const productCopy = {
  en: {
    nav: {
      portfolio: "Portfolio",
      attention: "Attention",
      myWork: "My Work",
      inbox: "Inbox",
      messages: "Messages",
      waiting: "Waiting",
      decisions: "Decisions",
      approvals: "Approvals",
      ideas: "Ideas",
      teams: "Teams",
      reviews: "Reviews",
      templates: "Templates",
      settings: "Settings",
      workspaces: "Workspaces",
    },
    shell: {
      search: "Search work, people, updates & more…",
      capture: "Quick capture",
      notifications: "Notifications",
      userMenu: "Open user menu",
      openNavigation: "Open navigation",
      closeNavigation: "Close navigation",
    },
    board: {
      breadcrumb: "Northstar Apparel / Product launch",
      title: "SS26 launch board",
      subtitle: "Products, compliance, content and storefront readiness",
      table: "Table",
      kanban: "Kanban",
      filter: "Filter",
      group: "Group",
      fields: "Fields",
      automate: "Automate",
      addItem: "Add item",
      item: "Item",
      owner: "Owner",
      status: "Status",
      priority: "Priority",
      due: "Due",
      resources: "Resources",
      updates: "Updates",
      planned: "Planned",
      working: "Working",
      review: "Review",
      done: "Done",
      blocked: "Blocked",
      noOwner: "Unassigned",
      today: "Today",
      saveView: "Save view",
      selected: "selected",
      bulkMove: "Move",
      assign: "Assign",
      clear: "Clear",
      empty: "No items match this view.",
      emptyAction: "Clear filters",
      density: "Density",
      progress: "68% ready",
      viewSaved: "Launch control",
      itemCount: "12 items",
      addBelow: "Add item",
      dragHint:
        "Drag to reorder. Use status control as a keyboard alternative.",
    },
    item: {
      type: "Task",
      close: "Close item",
      copyLink: "Copy link",
      more: "More actions",
      properties: "Properties",
      description: "Description",
      subitems: "Subitems",
      links: "Linked resources",
      activity: "Activity",
      comments: "Comments",
      addComment: "Write a browser-local sample note…",
      send: "Add local comment",
      assignees: "Assignees",
      dates: "Dates",
      created: "Created",
      dependency: "Dependency",
      openResource: "Open resource",
      complete: "Mark complete",
      checklist: "Completion checklist",
      addSubitem: "Add subitem",
      changesSaved: "Changes stay in this browser",
      following: "Following",
    },
    workspace: {
      overview: "Overview",
      boards: "Boards",
      updates: "Updates",
      metrics: "Metrics",
      teams: "Teams",
      links: "Links",
      editSummary: "Edit summary",
      addItem: "Add item",
      postUpdate: "Draft sample update",
      executive: "Executive summary",
      currentFocus: "Current focus",
      liveSignals: "Sample work signals",
      milestone: "Next milestone",
      latestUpdate: "Latest weekly update",
      decisions: "Decisions & approvals",
      recentActivity: "Recent activity",
      connected: "Sample resource links",
      viewBoard: "Open board",
    },
    focus: {
      myWorkTitle: "My Work",
      myWorkSubtitle: "The work that needs you, ordered by time and risk.",
      inboxTitle: "Inbox",
      inboxSubtitle:
        "A Workspace action queue for requests, assignments, and promoted email that needs tracked follow-through.",
      decisionsTitle: "Decision Center",
      decisionsSubtitle:
        "Resolve the choices that unblock progress in this workspace.",
      approvalsTitle: "Approval Center",
      approvalsSubtitle:
        "Review assets and requests without losing their context.",
      searchTitle: "Search",
      searchSubtitle:
        "Fictional scoped results across people, Workspaces, work, comments, updates and links.",
      templatesTitle: "Templates",
      templatesSubtitle:
        "Start proven operating workflows without adding hierarchy.",
      settingsTitle: "Integrations",
      settingsSubtitle:
        "Preview optional tools without connecting a provider account.",
      newCapture: "Capture item",
      searchPlaceholder: "Search TREVV…",
      noResults: "No matching work found.",
      today: "Today",
      upcoming: "Upcoming",
      overdue: "Overdue",
      noDate: "No date",
      waiting: "Waiting for review",
      complete: "Recently completed",
      needsDecision: "Needs decision",
      analyzing: "Analyzing",
      decided: "Decided history",
      dueSoon: "Due soon",
      requested: "Requested",
      connect: "Connect",
      configured: "Configured",
      preview: "Preview",
      useTemplate: "Use template",
    },
    auth: {
      signInTitle: "Explore the technical preview",
      signInSubtitle: "Open the fictional sample without entering credentials.",
      signUpTitle: "Preview TREVV onboarding",
      signUpSubtitle:
        "Walk through fictional setup choices without creating an account.",
      email: "Email (unavailable in preview)",
      password: "Password (never enter one in preview)",
      name: "Fictional name",
      signIn: "Authentication unavailable",
      create: "Account creation unavailable",
      demo: "Explore fictional sample workspace",
      noAccount: "Want to preview onboarding?",
      hasAccount: "Want to open the sample?",
      onboardingTitle: "Shape your operating system",
      onboardingSubtitle:
        "A few focused choices, then you land in a useful Portfolio.",
      continue: "Continue",
      back: "Back",
      organization: "Organization name",
      language: "Language",
      timezone: "Time zone",
      chooseWorkspaces: "Choose starter Workspaces",
      invite: "Invite your team",
      optional: "Optional",
    },
  },
} as const;
