import type { AttentionSignalDto } from "@founderhq/api-contract";
import { board, item, session, timestamp } from "./live-workflow-data";
export const issueSignals: AttentionSignalDto[] = [
  {
    id: "issue-overdue",
    organizationId: session.organization.id,
    portfolioId: "portfolio-one",
    workspaceId: board.workspaceId,
    entityType: "work_item",
    entityId: item.id,
    signalType: "overdue_work_item",
    severity: "critical",
    impact: 4,
    urgency: 5,
    responsibility: 1,
    reasonCode: "work_item.overdue",
    sourceFingerprint: "item-one:overdue",
    reason: "Ship the launch is overdue",
    recommendedAction: "Complete the task or agree a realistic deadline.",
    createdAt: timestamp,
    computedAt: timestamp,
    sourceEvidence: [
      {
        sourceType: "work_item",
        sourceId: item.id,
        capturedAt: timestamp,
        summary: "The launch date passed.",
        data: { dueDate: "2020-09-01", status: "not_started" },
      },
    ],
    metadata: {},
    version: 1,
  },
  {
    id: "issue-update",
    organizationId: session.organization.id,
    portfolioId: "portfolio-one",
    workspaceId: board.workspaceId,
    entityType: "workspace",
    entityId: board.workspaceId,
    signalType: "stale_workspace_update",
    severity: "medium",
    impact: 3,
    urgency: 3,
    responsibility: 1,
    reasonCode: "workspace.update_stale",
    sourceFingerprint: "workspace-one:stale",
    reason: "Launch has no recent update",
    recommendedAction: "Publish a concise Workspace update.",
    createdAt: timestamp,
    computedAt: timestamp,
    sourceEvidence: [
      {
        sourceType: "workspace",
        sourceId: board.workspaceId,
        capturedAt: timestamp,
        data: { staleAfterDays: 7 },
      },
    ],
    metadata: {},
    version: 2,
  },
];
